### ISSUE TITLE
Including warning information

### ISSUE THREAD

**Issue by douglascrp** [jpotts/alfresco-addon-descriptor#2]
I believe it would be useful to have something to let the user know if the addon installation can cause problems, including informations like:
"No original Alfresco resources have been overwritten"
"Original Alfresco resources have been overwritten".

In the second case, there could be a warning details, where the developer should include, for example, what resources were changed, or if there is any incompatibility with another know addon.

**Comment by jpotts** [comment]
One of the properties in the addon descriptor is a "review". The idea here is to allow developers to say to what extent they have checked the code against best practices. I had in mind Axel's list of best practices he developed for Order of the Bee. One of those best practices has to do with using public extension points and not touching Alfresco's files.

Developers are supposed to indicate whether they've reviewed their add-on against best practices themselves or if the add-on has been reviewed by an independent third-party. Order of the Bee could be one example, but it does not have to be OOTB.

Do you think this is enough or do we need to be more specific?

Regarding listing what resources have changed or incompatibility notes, do you think a freeform "notes" property would be enough or do we need specific properties with an enum of choices? If it is an enum, what are the valid choices for each case?

**Comment by douglascrp** [comment]
@jpotts I believe the review field is enough.
No need to add anything.
